Fix calls to assert_has_calls()
assert_has_calls() has been introduced in Python 3.6. Hence, tests
would fail with:

```
======================================================================
ERROR: test_persistent (client.commands.tests.persistent_test.PersistentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "pyre-check/client/commands/tests/persistent_test.py", line 55, in test_persistent
    run_null_server.assert_called_once()
  File "/usr/lib64/python3.5/unittest/mock.py", line 585, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once
```

Convert users to the API available in 3.5.