Remove unnecessary line in pyre2_wasm/build.sh
Summary:
When I try running `./build.sh`, I'm getting the following error. Removing this line seem to fix it

```
 dluo@dluo-mbp  ~/fbsource/fbcode/tools/pyre/pyre2/pyre2_wasm  ☿ 72057594037928291@default ±  ./build.sh
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling clap_builder v4.5.31
error[E0432]: unresolved import `unicase::eq`
  --> /Users/dluo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.31/src/util/mod.rs:38:16
   |
38 | pub(crate) use unicase::eq as eq_ignore_case;
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `eq` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `clap_builder` (lib) due to 1 previous error
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: cd "/Users/dluo/fbsource/fbcode/tools/pyre/pyre2/pyre2_wasm" && "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

Reviewed By: SamChou19815

Differential Revision: D70577434

fbshipit-source-id: b3bab61109d133781d92000c65a16cdb0b50dab7