Fix `flake8` linter errors
Summary:
[GitHub Actions `flake8` run log](https://github.com/facebook/pyre-check/runs/3248763481):
```
./client/commands/infer.py:13:1: F401 'subprocess' imported but unused
./client/commands/v2/check.py:12:1: F401 'tempfile' imported but unused
./client/commands/v2/check.py:14:1: F401 'typing.IO' imported but unused
Error: Process completed with exit code 1.
```

Reviewed By: grievejia

Differential Revision: D30133300

fbshipit-source-id: f997a57d6c91e352218046465c6b190530c5280d