Fix problematic breaking import
Summary:
### Context:
Tests break on Github even though they pass locally.
```
  File "/home/runner/work/pyre-check/pyre-check/client/commands/tests/expression_level_coverage_test.py", line 11, in <module>
    from tools.pyre.client.commands.expression_level_coverage import (
ModuleNotFoundError: No module named 'tools'
```

### Problem:
The above import statement is problematic so it should be removed.

### Solution:
We remove the import and update tests.

Reviewed By: stroxler

Differential Revision: D37554655

fbshipit-source-id: 9641f47e20105cd10ad706b4c8eb6ee6b5aa4217