Avoid cryptic exception upon partially unreadable filesystem
Summary:
While looking at T32309273, I noticed that, when confronted with an
unreadable file or directory (e.g. `chmod`'ed to `000`), Pyre would
fail with a cryptic result:

```
find: ‘./unreadable’: Permission denied
 ƛ Command '['find', '.', '-name', '*.pyre_configuration.local']' returned non-zero exit status 1.
 ƛ Traceback (most recent call last):
  File "tools/pyre/client/pyre.py", line 318, in main
  File "tools/pyre/client/commands/command.py", line 87, in run
  File "tools/pyre/client/commands/check.py", line 42, in _run
  File "tools/pyre/client/commands/command.py", line 166, in _call_client
  File "tools/pyre/client/commands/check.py", line 21, in _flags
  File "tools/pyre/client/commands/reporting.py", line 53, in _get_directories_to_analyze
  File "tools/pyre/client/filesystem.py", line 226, in list
  File "lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['find', '.', '-name', '*.pyre_configuration.local']' returned non-zero exit status 1.
```

While a hard exception is reasonable when a specific file we try to
open is unreadable, it is sometimes less of a concern if some
unrelated path is unreadable. The enumeration of the local config
paths is such a case. Hence, in that case, log errors rather than
raising an exception:
```
find: ‘./unreadable’: Permission denied
 ƛ Could not list `/.../unreadable`
 ƛ Could not list `/.../unreadable`
 ƛ No type errors found
```

Reviewed By: dkgi

Differential Revision: D9803348

fbshipit-source-id: 78ca887356080e207f84a22ae6a755c330d38585