Fix bug with how monitor terminates pyre
Summary:
Within the Monitor class, we were passing `self.analysis_directory`, a `str`, to the Stop
command, which expected an `AnalysisDirectory`. Pyre would still terminate, but not gracefully:
```
2019-02-22 08:36:57,999 INFO Update to local configuration at /data/users/mattdsouza/fbsource/fbcode/tools/pyre/.pyre_configuration.local
2019-02-22 08:36:57,999 INFO Update to local configuration at /data/users/mattdsouza/fbsource/fbcode/tools/pyre/.pyre_configuration.local
2019-02-22 08:36:58,000 INFO Stopping running pyre server.
2019-02-22 08:36:58,000 INFO Stopping running pyre server.
2019-02-22 08:36:58,000 INFO Not running pyre-monitor due to 'str' object has no attribute 'get_root'
2019-02-22 08:36:58,000 INFO Not running pyre-monitor due to 'str' object has no attribute 'get_root'
```
(an AttributeError gets thrown and caught within the monitor)

Reviewed By: shannonzhu

Differential Revision: D14185141

fbshipit-source-id: b71354826ed4b2550722e8f2fc1473e888cad6fc