Fix bad raise statement
Summary:
Seems like an editing error writing the code - the raise
has to be inside the except block. It's currently throwing exceptions
100% of the time.

I found this because a teammate asked about a stack
trace that was being printed with the error
```
RuntimeError: No active exception to reraise
```
and that seemed fishy :)

Reviewed By: connernilsen

Differential Revision: D40826864

fbshipit-source-id: fdd68e8745a8f170407bba5a54558e6d0c7bd13a