Replace invalid utf-8 bytes instead of raising an exception
Summary:
Pyre CLI traceback P673940033
Handle wrong bytes gracefully
```
>>> b'\x80abc'.decode("utf-8", "strict")
Traceback (most recent call last):
    ...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0:
  invalid start byte
>>> b'\x80abc'.decode("utf-8", "replace")
'\ufffdabc'
```

Reviewed By: grievejia

Differential Revision: D44562304

fbshipit-source-id: 4341d5866ff1b1a1957e5e209a0d954ace2f5644