Implement json parser and migrate taintConfiguration (#734)
Summary:
**Pre-submission checklist**
- [x] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [x] `pre-commit run`

Implements a json parsing module inside jsonParsing.ml that adds support for line and column numbers based on Jsonm. Removes all dependencies of taint configuration parsing on YoJSON which doesn't have any support for positions.

Since, Jsonm is pretty bare bone, implemented some utility functions inside a Util module that does pretty much what YoJSON's utility functions did.

There are minor changes in taintConfiguration to accomodate for the change.

This is the base part of changes that seek to remove dependency completely on YoJSON and switch to JSONM because YoJSON doesn't support line numbers in any way which we require for descriptive error messages.

Modifies and updates confirmationTest. Since we use a proper json parser, the json files for testing have been updated to use the proper json format as well.

Pull Request resolved: https://github.com/facebook/pyre-check/pull/734

Test Plan:
- make
- make test ( only failing test is due to the internal taint integration files -> you know why (: )
<details>

<summary>See test results</summary>

```
../scripts/generate-version-number.sh: line 16: greadlink: command not found
Build info: Darwin x86_64 @ Thu May 11 2023 (development build)
../scripts/generate-version-number.sh: line 30: hg: command not found
Git commit: ced2d4cdac4d2010ff9d11ee5eec2ec21365046a
dune build install -j auto --profile dev
File "dune", line 379, characters 2-43:
379 |   pyrelib.internalTaintIntegrationTestFiles
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Library "pyrelib.internalTaintIntegrationTestFiles" not found.
-> required by _build/default/decoratorsTest.exe
-> required by alias runtest in dune:359
................
Ran: 16 tests in: 0.67 seconds.
OK
............
Ran: 12 tests in: 0.42 seconds.
OK
................
Ran: 16 tests in: 0.38 seconds.
OK
.........................................
Ran: 41 tests in: 0.57 seconds.
OK
.........................................
Ran: 41 tests in: 0.74 seconds.
OK
...............................
Ran: 31 tests in: 0.45 seconds.
OK
................................
Ran: 32 tests in: 0.56 seconds.
OK
............
Ran: 12 tests in: 0.32 seconds.
OK
...............................
Ran: 31 tests in: 0.46 seconds.
OK
................
Ran: 16 tests in: 0.35 seconds.
OK
............
Ran: 12 tests in: 0.41 seconds.
OK
.
Ran: 1 tests in: 0.61 seconds.
OK
....
Ran: 4 tests in: 3.25 seconds.
OK
...............
Ran: 15 tests in: 4.43 seconds.
OK
...............
Ran: 15 tests in: 4.60 seconds.
OK
....
Ran: 4 tests in: 0.16 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 1.97 seconds.
OK
.
Ran: 1 tests in: 0.96 seconds.
OK
.
Ran: 1 tests in: 0.64 seconds.
OK
.
Ran: 1 tests in: 1.44 seconds.
OK
..
Ran: 2 tests in: 0.93 seconds.
OK
.
Ran: 1 tests in: 0.47 seconds.
OK
..........
Ran: 10 tests in: 8.32 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
..............
Ran: 14 tests in: 0.24 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
...
Ran: 3 tests in: 1.19 seconds.
OK
.
Ran: 1 tests in: 0.11 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
...
Ran: 3 tests in: 0.14 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
.........
Ran: 9 tests in: 0.21 seconds.
OK
..
Ran: 2 tests in: 0.15 seconds.
OK
....
Ran: 4 tests in: 0.20 seconds.
OK
..
Ran: 2 tests in: 0.14 seconds.
OK
......
Ran: 6 tests in: 0.17 seconds.
OK
..
Ran: 2 tests in: 0.13 seconds.
OK
........
Ran: 8 tests in: 0.18 seconds.
OK
..........
Ran: 10 tests in: 0.22 seconds.
OK
.
Ran: 1 tests in: 0.77 seconds.
OK
.......
Ran: 7 tests in: 0.20 seconds.
OK
..
Ran: 2 tests in: 0.86 seconds.
OK
.........
Ran: 9 tests in: 0.43 seconds.
OK
..
Ran: 2 tests in: 0.45 seconds.
OK
..
Ran: 2 tests in: 0.52 seconds.
OK
.....
Ran: 5 tests in: 0.36 seconds.
OK
.
Ran: 1 tests in: 0.68 seconds.
OK
....
Ran: 4 tests in: 1.61 seconds.
OK
.
Ran: 1 tests in: 5.57 seconds.
OK
........
Ran: 8 tests in: 4.05 seconds.
OK
...
Ran: 3 tests in: 0.72 seconds.
OK
....
Ran: 4 tests in: 0.49 seconds.
OK
..........
Ran: 10 tests in: 0.24 seconds.
OK
..
Ran: 2 tests in: 12.12 seconds.
OK
..
Ran: 2 tests in: 0.17 seconds.
OK
.............
Ran: 13 tests in: 0.34 seconds.
OK
.....
Ran: 5 tests in: 1.38 seconds.
OK
.................
Ran: 17 tests in: 12.13 seconds.
OK
...
Ran: 3 tests in: 0.15 seconds.
OK
................
Ran: 16 tests in: 3.29 seconds.
OK
.......
Ran: 7 tests in: 12.86 seconds.
OK
......
Ran: 6 tests in: 2.09 seconds.
OK
.......
Ran: 7 tests in: 0.20 seconds.
OK
..........
Ran: 10 tests in: 0.24 seconds.
OK
.......
Ran: 7 tests in: 5.43 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
....
Ran: 4 tests in: 0.76 seconds.
OK
.....
Ran: 5 tests in: 0.51 seconds.
OK
..
Ran: 2 tests in: 0.40 seconds.
OK
.
Ran: 1 tests in: 0.29 seconds.
OK
.
Ran: 1 tests in: 0.91 seconds.
OK
...................
Ran: 19 tests in: 8.82 seconds.
OK
...............
Ran: 15 tests in: 4.10 seconds.
OK
.
Ran: 1 tests in: 2.91 seconds.
OK
.....
Ran: 5 tests in: 0.21 seconds.
OK
.........................
Ran: 25 tests in: 8.24 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.....
Ran: 5 tests in: 0.18 seconds.
OK
............
Ran: 12 tests in: 35.36 seconds.
OK
.........................
Ran: 25 tests in: 18.38 seconds.
OK
...............................
Ran: 31 tests in: 1.35 seconds.
OK
.........
Ran: 9 tests in: 0.22 seconds.
OK
..
Ran: 2 tests in: 0.14 seconds.
OK
..................
Ran: 18 tests in: 2.56 seconds.
OK
........
Ran: 8 tests in: 3.67 seconds.
OK
.
Ran: 1 tests in: 0.27 seconds.
OK
.
Ran: 1 tests in: 1.55 seconds.
OK
..
Ran: 2 tests in: 0.47 seconds.
OK
............................................................................
Ran: 76 tests in: 1.22 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
.....
Ran: 5 tests in: 0.17 seconds.
OK
....
Ran: 4 tests in: 2.19 seconds.
OK
..
Ran: 2 tests in: 0.58 seconds.
OK
............
Ran: 12 tests in: 17.08 seconds.
OK
.
Ran: 1 tests in: 0.54 seconds.
OK
..
Ran: 2 tests in: 12.42 seconds.
OK
.....
Ran: 5 tests in: 3.67 seconds.
OK
......
Ran: 6 tests in: 2.81 seconds.
OK
.
Ran: 1 tests in: 4.54 seconds.
OK
..
Ran: 2 tests in: 3.56 seconds.
OK
........
Ran: 8 tests in: 10.70 seconds.
OK
......
Ran: 6 tests in: 5.11 seconds.
OK
....
Ran: 4 tests in: 2.13 seconds.
OK
..
Ran: 2 tests in: 3.24 seconds.
OK
...........
Ran: 11 tests in: 16.48 seconds.
OK
.
Ran: 1 tests in: 0.40 seconds.
OK
...............................
Ran: 31 tests in: 23.51 seconds.
OK
...
Ran: 3 tests in: 2.24 seconds.
OK
...
Ran: 3 tests in: 2.62 seconds.
OK
............
Ran: 12 tests in: 8.55 seconds.
OK
..
Ran: 2 tests in: 1.58 seconds.
OK
....
Ran: 4 tests in: 5.12 seconds.
OK
..
Ran: 2 tests in: 2.58 seconds.
OK
....
Ran: 4 tests in: 5.86 seconds.
OK
.
Ran: 1 tests in: 0.48 seconds.
OK
...
Ran: 3 tests in: 4.29 seconds.
OK
.
Ran: 1 tests in: 3.70 seconds.
OK
.
Ran: 1 tests in: 0.52 seconds.
OK
..
Ran: 2 tests in: 3.46 seconds.
OK
....
Ran: 4 tests in: 3.03 seconds.
OK
.
Ran: 1 tests in: 0.69 seconds.
OK
........
Ran: 8 tests in: 3.18 seconds.
OK
...
Ran: 3 tests in: 1.90 seconds.
OK
.
Ran: 1 tests in: 2.57 seconds.
OK
.....
Ran: 5 tests in: 5.53 seconds.
OK
.
Ran: 1 tests in: 2.85 seconds.
OK
..........
Ran: 10 tests in: 10.36 seconds.
OK
..............
Ran: 14 tests in: 8.20 seconds.
OK
.......
Ran: 7 tests in: 9.57 seconds.
OK
........
Ran: 8 tests in: 4.38 seconds.
OK
......
Ran: 6 tests in: 9.28 seconds.
OK
.
Ran: 1 tests in: 0.40 seconds.
OK
..
Ran: 2 tests in: 4.01 seconds.
OK
............
Ran: 12 tests in: 12.23 seconds.
OK
..
Ran: 2 tests in: 3.68 seconds.
OK
...
Ran: 3 tests in: 0.14 seconds.
OK
.
Ran: 1 tests in: 1.48 seconds.
OK
..
Ran: 2 tests in: 0.14 seconds.
OK
.....
Ran: 5 tests in: 0.17 seconds.
OK
..
Ran: 2 tests in: 0.14 seconds.
OK
......
Ran: 6 tests in: 23.52 seconds.
OK
...
Ran: 3 tests in: 0.17 seconds.
OK
....
Ran: 4 tests in: 0.16 seconds.
OK
.............
Ran: 13 tests in: 0.27 seconds.
OK
.........................
Ran: 25 tests in: 53.56 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.................
Ran: 17 tests in: 26.98 seconds.
OK
.....
Ran: 5 tests in: 0.17 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.....
Ran: 5 tests in: 0.25 seconds.
OK
.......
Ran: 7 tests in: 0.21 seconds.
OK
..........
Ran: 10 tests in: 0.26 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
..
Ran: 2 tests in: 0.15 seconds.
OK
...
Ran: 3 tests in: 0.15 seconds.
OK
.......Skipping low-level watchman API test due to exception: ("Server.Watchman.ConnectionError(\"Cannot find watchman exectuable under PATH: /Users/abishekvashok/projects/pyre-check/source/_build/install/default/bin:/Users/abishekvashok/.opam/4.14.0/bin:/Users/abishekvashok/.nvm/versions/node/v19.8.1/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/abishekvashok/Library/Android/sdk/tools:/Users/abishekvashok/Library/Android/sdk/platform-tools:/usr/local/opt/openjdk/bin:/usr/local/opt/binutils/bin\")")

Ran: 7 tests in: 0.22 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
...
Ran: 3 tests in: 0.17 seconds.
OK
..
Ran: 2 tests in: 0.15 seconds.
OK
...
Ran: 3 tests in: 0.16 seconds.
OK
...............
Ran: 15 tests in: 0.30 seconds.
OK
..
Ran: 2 tests in: 0.25 seconds.
OK
.
Ran: 1 tests in: 1.70 seconds.
OK
...
Ran: 3 tests in: 0.15 seconds.
OK
.......
Ran: 7 tests in: 2.33 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.............................
Ran: 29 tests in: 15.11 seconds.
OK
..
Ran: 2 tests in: 0.83 seconds.
OK
.
Ran: 1 tests in: 3.00 seconds.
OK
..............................
Ran: 30 tests in: 20.82 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.02 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
.
Ran: 1 tests in: 1.22 seconds.
OK
..................................................................................................................
Ran: 114 tests in: 54.85 seconds.
OK
....
Ran: 4 tests in: 0.82 seconds.
OK
.....
Ran: 5 tests in: 18.27 seconds.
OK
.
Ran: 1 tests in: 0.12 seconds.
OK
.......
Ran: 7 tests in: 9.23 seconds.
OK
..
Ran: 2 tests in: 0.16 seconds.
OK
..
Ran: 2 tests in: 2.23 seconds.
OK
..
Ran: 2 tests in: 0.16 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.15 seconds.
OK
.....
Ran: 5 tests in: 0.23 seconds.
OK
...............................
Ran: 31 tests in: 52.49 seconds.
OK
.
Ran: 1 tests in: 0.14 seconds.
OK
.
Ran: 1 tests in: 0.15 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
.
Ran: 1 tests in: 0.13 seconds.
OK
......
Ran: 6 tests in: 1.09 seconds.
OK
.............
Ran: 13 tests in: 0.57 seconds.
OK
.......
Ran: 7 tests in: 0.86 seconds.
OK
..........
Ran: 10 tests in: 0.32 seconds.
OK
.[2023-05-15 18:04:47] Dumping a saved state deptable.
Finished SQL Transaction took 0.00s
Lookup of existing rows took 95 us
Wrote 10 new rows
Updated 0 existing rows
Finished closing SQL connection took 0.00s
Writing dependency file with sqlite took 0.01s
.............
Ran: 14 tests in: 7.97 seconds.
OK
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Ran: 7496 tests in: 147.70 seconds.
OK
make: *** [test] Error 1
```

</details>

- Run on newly compiled binary on exercise1 in pysa_tutorial (`python3 -m pyre-check.client.pyre -n analyze --no-verify`):
<img width="1179" alt="Screenshot 2023-05-06 at 1 17 36 PM" src="https://user-images.githubusercontent.com/8947010/236610948-15b870e3-fa0e-411f-abac-ab5a20a10cdb.png">

Fixes part of https://github.com/MLH-Fellowship/pyre-check/issues/82

Low level notes:
- This is the root PR that all other PRs relating to the issue mentioned above can/will/might be stacked on top of.
- The pysa Github actions were failing before this PR as well.

Reviewed By: alexkassil

Differential Revision: D46143354

Pulled By: arthaud

fbshipit-source-id: d9bee5dcc3c7e7e9bfbfff532af6d21dfa2af39f