Mangle names of private attributes in preprocessing
Summary:
This diff handles private attributes using name mangling in a consistent way as the Python runtime.

See docs:
https://docs.python.org/3/tutorial/classes.html#private-variables
https://docs.python.org/3/reference/expressions.html?highlight=mangling#atom-identifiers

> Private name mangling: When an identifier that textually occurs in a class definition begins with two or more underscore characters and does not end in two or more underscores, it is considered a private name of that class. Private names are transformed to a longer form before code is generated for them. The transformation inserts the class name, with leading underscores removed and a single underscore inserted, in front of the name. For example, the identifier __spam occurring in a class named Ham will be transformed to _Ham__spam. This transformation is independent of the syntactical context in which the identifier is used.

We've received reports that our existing lack of support for this has missed SEVs that could have been stopped by the type checker: https://fb.workplace.com/groups/pyreqa/permalink/3217458681677275/
SEV: S205964

This work also blocks some pain points around being explicit in error messages if privacy is the reason we're reporting something that appears to be defined as undefined (T96900444) and fixing buggy behavior reporting annotated `self` as not having access to private attributes (T96900765).

Note: some follow-ups on this diff include refactoring our checks for `is_private_attribute` and making this info available at error time (ie., restack D30091928)

------

Some fun runtime examples of name mangling:

```
>>> class Foo:
...     def __init__(self) -> None:
...             self._name = "hi"
...
>>> f = Foo()
>>> f._name
'hi'
>>> class Bar:
...     def __init__(self) -> None:
...             self.__name = "hi"
...
>>> b = Bar()
>>> b.__name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bar' object has no attribute '__name'
>>> class Baz:
...     def __init__(self) -> None:
...             self.___name = "hi"
...
>>> baz = Baz()
>>> baz.___name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Baz' object has no attribute '___name'
>>> dir(baz)
['_Baz___name', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']

>>> class Foo:
...     __a = 1
...
>>> class Bar(Foo):
...     def test(self) -> None:
...             temp = self.__a
...
>>> Bar().test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in test
AttributeError: 'Bar' object has no attribute '_Bar__a'

>>> def __toplevel(x: int) -> int:
...     return x
...
>>> class Foo:
...     def test(self):
...             print(__toplevel(1))
...
>>> Foo().test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in test
NameError: name '_Foo__toplevel' is not defined
```

Reviewed By: grievejia

Differential Revision: D30146161

fbshipit-source-id: 12439d9f94995361076924193e2c16ab85521f6c