Remove leading underscore in __test_sink, __test_source, etc.
Summary:
The naming convention for these test functions will break if we start handling private names correctly in classes, see docs on private name mangling: https://docs.python.org/3/reference/expressions.html?highlight=mangling

At runtime, it's impossible to access a function named with a leading double underscore from inside a class:

```
>>> def __toplevel(x: int) -> int:
...     return x
...
>>> class Foo:
...     def test(self):
...             print(__toplevel(1))
...
>>> Foo().test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in test
NameError: name '_Foo__toplevel' is not defined
```

This diff is a no-op except adjusting the naming of these test helpers to lead with a single underscore instead.

Includes: `__test_sink`, `__test_source`
still need to do: `__global_sink`, `__user_controlled`, `__tito`

Reviewed By: gbleaney

Differential Revision: D30150334

fbshipit-source-id: 271814d20ef9df6984531bffe8158151cfd91574