Add context to __setitem__ errors
Summary:
I borrowed the term "item assignment" from the runtime:
```
$ python3.12
>>> 1[0] = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object does not support item assignment
```

Reviewed By: stroxler

Differential Revision: D70829906

fbshipit-source-id: 9f04f29ff66d58245e276ad107631b09c3a93493