suppress missing type parameters errors by default
Summary:
This restores compatibility with mypy in this class of error.

Example:
```
from typing import Dict
def f(x: Dict) -> None:
    reveal_type(x)
mypy a.py
a.py:3: error: Revealed type is 'builtins.dict[Any, Any]'
```

Reviewed By: dkgi

Differential Revision: D10154994

fbshipit-source-id: 6c5c38de458d1283525997ce78c706b2857fada8