Fix up error when missing configuration
Summary:
If the configuration is missing or it errors before this - we will error on pyre infer with something like:

```
UnboundLocalError: local variable 'configuration' referenced before assignment
```

If we make sure that `configuration` is always a variable before the `try` statement, we get an error like:

```
Invalid configuration: Configuration was not validated
```

Reviewed By: shannonzhu

Differential Revision: D15318843

fbshipit-source-id: a779feee24c2b95173020e34f68b08181ed11ad0