Fix subscript test case syntax
Summary:
It turns out that Python has a pretty wild syntactic restriction: you
can't use a bare walrus operator inside of a subscript key in an
assignment target.

What's wild is that semantically this isn't a restriction, because if you
just put parentheses around the same expression it will run just fine; here's
a demonstration in the repl:
```
> python3
Python 3.8.9 (default, Jul 27 2021, 02:53:04)
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {}
>>> k = "k"
>>> d[k0 := k] = "v"
  File "<stdin>", line 1
    d[k0 := k] = "v"
         ^
SyntaxError: invalid syntax
>>> d[(k0 := k)] = "v"
>>> k0
'k'
```

Reviewed By: samwgoldman

Differential Revision: D56736830

fbshipit-source-id: c2f41360fe3da97c8aaeb1a358f029e4a5108e7c