Add OUNIT_SHARDS="1" to unit test instructions
Summary:
Many of our tests that rely on a scratch project can't run properly
unless OUNIT_SHARDS="1" is set.

Noting this in CONTRIBUTING.md along with a brief description of
what happens if you forget the flag, so that if someone forgets it
the errors they run into might jog their memory.

In case anyone was curious, this is the kind of error you can run
into if you forget to set one shard - it's not at all obvious.
```
> dune exec analysis/test/inferenceTest.ml
Error: execve:
/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/default/analysis/test/inferenceTest.ml:
Permission denied
stroxler@devvm048 : /data/users/stroxler/fbsource/fbcode/tools/pyre/source
> dune exec analysis/test/inferenceTest.exe
FEEEEE
==============================================================================
Error: inference:5:infer_fields.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#01.log", line 363, characters 1-1:
Error: inference:5:infer_fields (in the log).

Raised at file "hack_parallel/hack_parallel/heap/sharedMem.ml", line 1205, characters 14-29
Called from file "src/list.ml", line 387, characters 13-17
Called from file "src/list.ml" (inlined), line 418, characters 15-31
Called from file "analysis/classHierarchy.ml" (inlined), line 159, characters 9-38
Called from file "analysis/classHierarchy.ml", line 156, characters 6-122
Called from file "analysis/classMetadataEnvironment.ml", line 46, characters 8-203
Called from file "src/option.ml", line 265, characters 23-28
Called from file "analysis/environment.ml", line 217, characters 24-81
Called from file "analysis/classMetadataEnvironment.ml", line 169, characters 4-55
Called from file "analysis/attributeResolution.ml", line 1534, characters 20-180
Called from file "src/option.ml", line 265, characters 23-28
Called from file "analysis/attributeResolution.ml", line 1539, characters 18-235
Called from file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 36, characters 4-11
Called from file "src/sequence.ml", line 706, characters 17-25
Called from file "src/sequence.ml", line 278, characters 10-16
Called from file "analysis/attributeResolution.ml", line 1598, characters 10-354
Called from file "analysis/globalResolution.ml", line 257, characters 2-255
Called from file "analysis/globalResolution.ml", line 545, characters 4-174
Called from file "src/list.ml", line 252, characters 13-16
Called from file "analysis/typeCheck.ml", line 1453, characters 16-198
Called from file "analysis/typeCheck.ml", line 1713, characters 8-213
Called from file "analysis/inference.ml", line 227, characters 16-50
Called from file "analysis/inference.ml", line 460, characters 39-58
Called from file "analysis/inference.ml", line 854, characters 25-60
Called from file "src/list.ml", line 395, characters 13-17
Called from file "src/list.ml" (inlined), line 418, characters 15-31
Called from file "analysis/inference.ml" (inlined), line 906, characters 77-94
Called from file "analysis/inference.ml", line 906, characters 18-94
Called from file "analysis/test/inferenceTest.ml", line 200, characters 2-57
Called from file "analysis/test/inferenceTest.ml", line 752, characters 23-59
Called from file "analysis/test/inferenceTest.ml", line 763, characters 2-161
Called from file "test/test.ml", line 79, characters 6-18
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

Not_found
------------------------------------------------------------------------------
==============================================================================
Error: inference:1:missing_parameter.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#02.log", line 14, characters 1-1:
Error: inference:1:missing_parameter (in the log).

Raised at file "src/error.ml" (inlined), line 8, characters 14-30
Called from file "src/option.ml", line 136, characters 4-21
Called from file "analysis/test/inferenceTest.ml", line 193, characters 23-46
Called from file "analysis/test/inferenceTest.ml", line 209, characters 15-51
Called from file "analysis/test/inferenceTest.ml" (inlined), line 216, characters 32-64
Called from file "analysis/test/inferenceTest.ml", line 242, characters 2-195
Called from file "test/test.ml", line 79, characters 6-18
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

"Option.value_exn None"
------------------------------------------------------------------------------
==============================================================================
Error: inference:4:missing_attribute.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#01.log", line 261, characters 1-1:
Error: inference:4:missing_attribute (in the log).

Raised by primitive operation at file "hack_parallel/hack_parallel/heap/sharedMem.ml", line 613, characters 16-39
Called from file "set.ml", line 376, characters 35-38
Called from file "set.ml", line 376, characters 25-33
Called from file "set.ml", line 376, characters 25-33
Called from file "set.ml", line 376, characters 25-33
Called from file "hack_parallel/hack_parallel/heap/sharedMem.ml", line 1219, characters 4-28
Called from file "list.ml", line 110, characters 12-15
Called from file "src/list0.ml" (inlined), line 25, characters 16-35
Called from file "service/dependencyTrackedMemory.ml", line 148, characters 8-62
Called from file "analysis/unannotatedGlobalEnvironment.ml" (inlined), line 993, characters 17-58
Called from file "analysis/unannotatedGlobalEnvironment.ml", line 987, characters 14-376
Called from file "profiling.ml", line 90, characters 25-29
Called from file "profiling.ml", line 131, characters 15-19
Called from file "analysis/unannotatedGlobalEnvironment.ml", line 983, characters 8-1023
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/classHierarchyEnvironment.ml", line 268, characters 4-132
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "analysis/environment.ml", line 368, characters 6-174
Called from file "test/test.ml", line 2617, characters 4-159
Called from file "test/test.ml", line 2772, characters 6-67
Called from file "analysis/test/inferenceTest.ml", line 185, characters 6-53
Called from file "analysis/test/inferenceTest.ml", line 209, characters 15-51
Called from file "analysis/test/inferenceTest.ml" (inlined), line 673, characters 32-64
Called from file "analysis/test/inferenceTest.ml", line 674, characters 2-272
Called from file "test/test.ml", line 79, characters 6-18
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

SharedMem.C_assertion_failure("hh_shared.c : 1999")
------------------------------------------------------------------------------
==============================================================================
Error: inference:3:missing_global.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#01.log", line 183, characters 1-1:
Error: inference:3:missing_global (in the log).

Raised at file "src/error.ml" (inlined), line 8, characters 14-30
Called from file "src/option.ml", line 136, characters 4-21
Called from file "analysis/test/inferenceTest.ml", line 193, characters 23-46
Called from file "analysis/test/inferenceTest.ml", line 209, characters 15-51
Called from file "analysis/test/inferenceTest.ml" (inlined), line 623, characters 32-64
Called from file "analysis/test/inferenceTest.ml", line 624, characters 2-257
Called from file "test/test.ml", line 79, characters 6-18
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

"Option.value_exn None"
------------------------------------------------------------------------------
==============================================================================
Error: inference:2:missing_return.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#01.log", line 105, characters 1-1:
Error: inference:2:missing_return (in the log).

Raised at file "src/error.ml" (inlined), line 8, characters 14-30
Called from file "src/option.ml", line 136, characters 4-21
Called from file "analysis/test/inferenceTest.ml", line 193, characters 23-46
Called from file "analysis/test/inferenceTest.ml", line 209, characters 15-51
Called from file "analysis/test/inferenceTest.ml" (inlined), line 412, characters 32-64
Called from file "analysis/test/inferenceTest.ml", line 413, characters 2-168
Called from file "test/test.ml", line 79, characters 6-18
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

"Option.value_exn None"
------------------------------------------------------------------------------
==============================================================================
Error: inference:0:backward.

File "/data/users/stroxler/fbsource/fbcode/tools/pyre/source/_build/oUnit-inference-devvm048.frc0.facebook.com#01.log", line 5, characters 1-1:
Error: inference:0:backward (in the log).

File "analysis/test/inferenceTest.ml", line 95, characters 1-1:
Error: inference:0:backward (in the code).

expected:   Bottom: false
  Expected return: typing.Any
Update
  Types:
    x -> [Base: (int: m); Attributes: []]
  Errors:

but got:   Bottom: false
  Expected return: typing.Any
  Types:

  Errors:

differences:
 --- /dev/fd/63	2021-03-30 16:53:33.795150607 -0700
+++ /dev/fd/62	2021-03-30 16:53:33.795150607 -0700
@@ -1,7 +1,7 @@
   Bottom: false
   Expected return: typing.Any
   Types:
-    x -> [Base: (int: m); Attributes: []]
+
   Errors:

------------------------------------------------------------------------------
Ran: 6 tests in: 0.72 seconds.
FAILED: Cases: 6 Tried: 6 Errors: 5 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
```

Reviewed By: grievejia

Differential Revision: D27449625

fbshipit-source-id: 913e510fc82911785d2dabb4fadbd83792493059