Support alternate build dirs using env var
Summary:
On my local machine, I've started symlinking `fbcode/tools/pyre/source/_build`
to `~/_pyre_build` because that's the easiest way to push it out of eden.

This breaks the Pysa tests:
```
BASH> make test 2> >(grep -v 'ld: warning:')
Build info: Darwin arm64 @ Wed Dec 13 2023 (development build)
HG revision: 71f62afe7350d009b9095ddf26281935172dc6da
dune build install -j auto --profile dev
File "interprocedural_analyses/taint/test/dune", line 23, characters 2-17:
23 |   integrationTest
       ^^^^^^^^^^^^^^^
F
==============================================================================
Error: taint:0:paths_found.

File "/Users/stroxler/_pyre_build/default/interprocedural_analyses/taint/test/oUnit-taint-stroxler-mbp#01.log", line 2, characters 1-1:
Error: taint:0:paths_found (in the log).

Raised at OUnitAssert.assert_failure in file "src/lib/ounit2/advanced/oUnitAssert.ml", line 45, characters 2-27
Called from OUnitRunner.run_one_test.(fun) in file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

No test paths to check.
------------------------------------------------------------------------------
Ran: 1 tests in: 0.11 seconds.
FAILED: Cases: 1 Tried: 1 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
.
Ran: 1 tests in: 0.53 seconds.
OK
.......
Ran: 7 tests in: 0.67 seconds.
OK
..
Ran: 2 tests in: 0.28 seconds.
OK
File "dune", line 415, characters 2-30:
415 |   internalTaintIntegrationTest)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
F
==============================================================================
Error: taint:0:paths_found.

File "/Users/stroxler/_pyre_build/default/oUnit-taint-stroxler-mbp#01.log", line 2, characters 1-1:
Error: taint:0:paths_found (in the log).

Raised at OUnitAssert.assert_failure in file "src/lib/ounit2/advanced/oUnitAssert.ml", line 45, characters 2-27
Called from OUnitRunner.run_one_test.(fun) in file "src/lib/ounit2/advanced/oUnitRunner.ml", line 83, characters 13-26

No test paths to check.
------------------------------------------------------------------------------
Ran: 1 tests in: 0.01 seconds.
FAILED: Cases: 1 Tried: 1 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
.............................
Ran: 29 tests in: 3.26 seconds.
OK
..............................
Ran: 30 tests in: 4.75 seconds.
OK
.....
Ran: 5 tests in: 5.08 seconds.
OK
...............................
Ran: 31 tests in: 15.33 seconds.
OK
make: *** [test] Error 1
```

The problem here is that `end_to_end_test_paths` always searches upward
from the current working directory to find the pyre code root (from which
it finds integration test fixtures), and dune runs tests from inside of the
build directory. As a result, it fails if you symlink the build directory
outside of the code root.

This might be a long-term problem for Pysa, since I'm not sure whether there
will be a good way to make this work well on both dune and buck (I'm fairly
sure that building with buck is going to break it similar to me moving the
dune build root).

One solution - which will work even for buck but might not work out of the box
with automatic CI that naively runs `buck test` - is to just allow the user to
manually specify an environment variable. This is a great solution for my local
development, so going with that for now.

I suspect I could comb through dune docs and find a way to do this with dune
rather than an environment variable, but given the backdrop of us maybe wanting
to move to buck anyway this seems like a poor use of scarce time.

Reviewed By: alexkassil

Differential Revision: D52123954

fbshipit-source-id: e550d830b5d9d4a84d95c2d36908b46726f6b19e