Re-introduce main method in upgrade module
Summary:
If I'm understanding correctly, the way buck builds modules relies on a `main` being importable from the specified main module.

Otherwise this will be broken when built and packaged for open source:

```
szhu@szhu-mbp tmp % pyre-upgrade fixme-single .
Traceback (most recent call last):
  File "/usr/local/bin/pyre-upgrade", line 6, in <module>
    from pyre_check.tools.upgrade.upgrade import main
ImportError: cannot import name 'main' from 'pyre_check.tools.upgrade.upgrade' (/usr/local/lib/python3.7/site-packages/pyre_check/tools/upgrade/upgrade.py)
szhu@szhu-mbp tmp %
```

Reviewed By: MaggieMoss

Differential Revision: D19145223

fbshipit-source-id: f9458838cf8bc060e366f3ca6f24e81482a8ec95