Print inference required fields in error json
Summary:
Diagnosing some remaining failing client tests - I believe the buck dependency bug has been resolved, which leaves only a few tests that have been legitimately broken in the interim.

TestX: https://www.internalfb.com/intern/test/281474998888320?ref_report_id=0

I'm aware we're moving to a new error object in the v2 client, and also that we want to structurally separate out inference errors in the backend from type check errors. Until we make that happen and a run of `pyre infer` outputs different objects than a run of `pyre`, the error printing logic still is shared.

Like other pyre commands, infer supports both (1) printing errors to stdout, and (2) taking input from stdin. Our tests currently use these two features to test one another - to fix this I considered removing one or both functionality but it appears the `--json` flag is still in use. Either way, IMO it makes sense that we should still allow users (and/or us, when debugging) to print pyre infer results to stdout, and when doing so we should be printing pyre infer relevant information.

If output clutter is a concern, I could override the print method in the infer command to handle legacy errors.

previously failing behavior:
```
(base) [szhu@devvm1864.prn3 ~/fbsource/fbcode] pyre -l tools/pyre infer --print-only | pyre -l tools/pyre infer --in-place --json
ƛ Using unstable client. If you encounter issues, you can use the stable client via `export PYRE_CLIENT_RELEASE="stable"`.
ƛ Using unstable client. If you encounter issues, you can use the stable client via `export PYRE_CLIENT_RELEASE="stable"`.
ƛ Found 38 type errors!
ƛ Traceback (most recent call last):
  File "tools/pyre/client/pyre.py", line 116, in run_pyre_command
    exit_code = command.run().exit_code()
  File "tools/pyre/client/commands/infer.py", line 526, in run
    errors = self._get_errors(result, bypass_filtering=True, from_stdin=from_stdin)
  File "tools/pyre/client/commands/infer.py", line 573, in _get_errors
    errors = self._relativize_errors(relative_root, self._parse_raw_errors(result))
  File "tools/pyre/client/commands/reporting.py", line 67, in _parse_raw_errors
    errors.append(LegacyError.create(error, ignore_error=False))
  File "tools/pyre/client/error.py", line 111, in create
    inference=error["inference"],
KeyError: 'inference'
```

note: accidentally included a run of pyre infer into this diff. going to just leave in the extra annotations, but if anyone feels strongly I can go in and strip them out.

Reviewed By: grievejia

Differential Revision: D25124057

fbshipit-source-id: 3e30307763188c3ff95310e81503d4bdd8894056